name: Build, push, and deploy to dev (manual)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and push
    uses: ./.github/workflows/.test-and-build.yml
    permissions:
      contents: read
      id-token: write
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      READER_TOKEN: ${{ secrets.READER_TOKEN }}

  deploy-dev:
    name: Deploy to NAIS (dev)
    needs: build
    uses: ./.github/workflows/.deploy-to-nais.yml
    with:
      NAIS_ENV: dev
      IMAGE: ${{ needs.build.outputs.IMAGE }}
